name: Cheremushki

services:
  db:
    image: postgres:17-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # Remove for production deployment, only for local development (live code + hot reload)
      - ./backend:/src
      - media:/src/media
      - staticfiles:/src/staticfiles
    expose:
      - "8000"
    # Remove for production deployment, only for local development
    ports:
      - "8000:8000"
    container_name: backend
    env_file: .env
    command: bash ./scripts/run_backend_local.sh
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    command: celery -A config.celery:app worker -Q generation,default -l info
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/src

  celery_flower:
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config.celery:app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/src
    restart: "no"

  celery_beat:
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A config.celery:app beat -l info
    volumes:
      - ./backend:/src
    restart: "no"

  mailcatcher:
    image: sj26/mailcatcher
    container_name: mailcatcher
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP-Port
      - "1080:1080"  # Webinterface

volumes:
  postgres-db:
  media:
  staticfiles: