# Generated by Django 6.0.7 on 2026-08-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_unique_telegram_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramForumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("thread_id", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Forum-Topic",
                "verbose_name_plural": "Telegram Forum-Topics",
            },
        ),
        migrations.AddField(
            model_name="telegraminvite",
            name="profile_content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 über Caption, Keyboard und Bild des zuletzt gesendeten Posts. Stimmt der Hash, entfällt der Telegram-Call komplett.",
                max_length=64,
            ),
        ),
    ]
