# Generated by Django 6.0.7 on 2026-08-27 06:47

from django.db import migrations, models
from django.db.models import F


def backfill_invite_sent_at(apps, schema_editor):
    """Bestandsdaten: Ein vorhandener Einladungslink heißt, die Mail ist raus.

    Ohne diesen Schritt gilt jedes Altkonto als 'noch nicht eingeladen' und
    bekommt beim nächsten Speichern des Profils eine zweite Einladungsmail –
    mit einem neuen Link, der den alten nicht ersetzt.

    Fallback auf created_at, weil der echte Versandzeitpunkt nicht mehr
    rekonstruierbar ist. Für das Gate zählt allein 'nicht null'.
    """
    TelegramInvite = apps.get_model("bot", "TelegramInvite")
    TelegramInvite.objects.filter(invite_sent_at__isnull=True).exclude(
        invite_link__isnull=True
    ).exclude(invite_link="").update(invite_sent_at=F("created_at"))


def clear_invite_sent_at(apps, schema_editor):
    """Rückwärts ist nichts zu tun – die Spalte verschwindet mit der Migration.

    Explizit statt migrations.RunPython.noop, damit `migrate bot 0004` ohne
    Sonderbehandlung durchläuft und der Rollback testbar bleibt.
    """


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_telegramforumtopic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegraminvite",
            name="invite_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt des Einladungsversands. Das Feld verhindert einen zweiten Versand, auch wenn das Profil erneut gespeichert wird. Nicht durch invite_link ersetzbar, der Link entsteht auch bei einem Retry, dessen Mailversand danach scheitert.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_invite_sent_at, clear_invite_sent_at),
    ]
