# Generated by Django 6.0.7 on 2026-07-29 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=80, unique=True
                    ),
                ),
                ("headline", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                (
                    "profession",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("company", models.CharField(blank=True, default="", max_length=120)),
                ("position", models.CharField(blank=True, default="", max_length=120)),
                ("bio", models.TextField(blank=True, default="")),
                ("can_help_with", models.TextField(blank=True, default="")),
                ("looking_for", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                (
                    "telegram_username",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("website_url", models.URLField(blank=True, default="")),
                (
                    "contact_mode",
                    models.CharField(
                        choices=[
                            ("direct", "Direkt"),
                            ("request", "Anfrage"),
                            ("group", "Gruppe"),
                            ("closed", "Geschlossen"),
                        ],
                        default="request",
                        max_length=16,
                    ),
                ),
                ("telegram_group_url", models.URLField(blank=True, default="")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "avatar_original",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/originals/"
                    ),
                ),
                ("avatar_position_x", models.FloatField(default=0.5)),
                ("avatar_position_y", models.FloatField(default=0.5)),
                ("avatar_scale", models.FloatField(default=1.0)),
                ("avatar_crop_size", models.FloatField(default=1.0)),
                ("is_directory_visible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliederprofil",
                "verbose_name_plural": "Mitgliederprofile",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("sent", "Gesendet"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="profiles.memberprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontaktanfrage",
                "verbose_name_plural": "Kontaktanfragen",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_profile"),
                        name="unique_contact_request_per_pair",
                    )
                ],
            },
        ),
    ]
