# Generated by Django 6.0.7 on 2026-07-29 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="updated_at",
        ),
    ]
