# Generated by Django 6.0.7 on 2026-08-04 04:31

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.profiles.models.avatar_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="memberprofile",
            name="avatar_original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.profiles.models.avatar_original_upload_to,
            ),
        ),
    ]
