# Generated by Django 6.0.7 on 2026-08-04 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalIdentifier",
        ),
    ]
