# Generated by Django 6.1 on 2026-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_globalidentifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
